VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Cluster"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Copyright (c) 2015-2023 Jeffrey J. Long. All rights reserved

'@Folder("Relationship Visualizer.Sheets.Cluster")

'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public label As String
'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public tooltip As String
'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public styleName As String
'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public attributes As String
'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public subclusters As Dictionary

