VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Style"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Copyright (c) 2015-2022 Jeffrey J. Long. All rights reserved

'@Folder("Relationship Visualizer.Sheets.Styles")

'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public styleType As String
'@Ignore VariableNotUsed, MoveFieldCloserToUsage, EncapsulatePublicField
Public styleFormat As String



