Attribute VB_Name = "modConstants"
' Copyright (c) 2015-2024 Jeffrey J. Long. All rights reserved

'@Folder("Relationship Visualizer.Bootstrap")
'@IgnoreModule UseMeaningfulName

Option Explicit

Public Const PRODUCT_TEMPDIR As String = "ExcelToGraphviz"

' Worksheet names used in export/import code.
' Worksheet names can be localized.
Public Const WORKSHEET_DATA As String = "data"
Public Const WORKSHEET_GRAPH As String = "graph"
Public Const WORKSHEET_SETTINGS As String = "settings"
Public Const WORKSHEET_SOURCE As String = "source"
Public Const WORKSHEET_SQL As String = "sql"
Public Const WORKSHEET_STYLES As String = "styles"
Public Const WORKSHEET_SVG As String = "svg"

' Default language file
Public Const WORKSHEET_LOCALE_MASTER As String = "locale_en-US"

' Row indicator characters
Public Const FLAG_ERROR As String = "!"
Public Const FLAG_COMMENT As String = "#"

' Commonly reused strings
Public Const CLOSE_BRACE As String = "}"
Public Const COMMA As String = ","
Public Const GRAPHVIZ_EXTENSION As String = ".gv"
Public Const GREATER_THAN As String = ">"
Public Const LESS_THAN As String = "<"
Public Const NEWLINE As String = "\n"
Public Const OPEN_BRACE As String = "{"
Public Const SEMICOLON As String = ";"
Public Const ONE_SECOND_DELAY As String = "00:00:01"

#If Mac Then
Public Const COLON As String = ":"
#End If
Public Const UTF8_CHARSET As String = "UTF-8"

' Keywords
Public Const KEYWORD_NODE As String = "NODE"
Public Const KEYWORD_EDGE As String = "EDGE"
Public Const KEYWORD_GRAPH As String = "GRAPH"
Public Const KEYWORD_CLUSTER As String = "CLUSTER"

' Graphviz layouts
Public Const LAYOUT_CIRCO As String = "circo"
Public Const LAYOUT_DOT As String = "dot"
Public Const LAYOUT_FDP As String = "fdp"
Public Const LAYOUT_NEATO As String = "neato"
Public Const LAYOUT_OSAGE As String = "osage"
Public Const LAYOUT_PATCHWORK As String = "patchwork"
Public Const LAYOUT_SFDP As String = "sfdp"
Public Const LAYOUT_TWOPI As String = "twopi"

' Row Types
Public Const TYPE_BLANK_ROW As String = "BLANK_ROW"
Public Const TYPE_NODE As String = "node"
Public Const TYPE_EDGE As String = "edge"
Public Const TYPE_SUBGRAPH_OPEN As String = "subgraph-open"
Public Const TYPE_SUBGRAPH_CLOSE As String = "subgraph-close"
Public Const TYPE_GRAPH As String = "graph"
Public Const TYPE_KEYWORD As String = "keyword"
Public Const TYPE_NATIVE As String = "native"

' Toggle switch values
Public Const TOGGLE_INCLUDE As String = "Include"
Public Const TOGGLE_EXCLUDE As String = "Exclude"

Public Const TOGGLE_YES As String = "yes"
Public Const TOGGLE_NO As String = "no"

Public Const TOGGLE_KEEP As String = "keep"
Public Const TOGGLE_DELETE As String = "delete"

Public Const TOGGLE_ON As String = "on"
Public Const TOGGLE_OFF As String = "off"

Public Const TOGGLE_SHOW As String = "show"
Public Const TOGGLE_HIDE As String = "hide"

Public Const TOGGLE_AUTO As String = "auto"
Public Const TOGGLE_MANUAL As String = "manual"

Public Const TOGGLE_DIRECTED As String = "directed"
Public Const TOGGLE_UNDIRECTED As String = "undirected"

Public Const TOGGLE_BLANK_USE_DEFAULT As String = "default"
Public Const TOGGLE_BLANK_USE_BLANK As String = "blank"

Public Const IMPORT_APPEND As String = "append"
Public Const IMPORT_REPLACE As String = "replace"

' Color scheme constants
Public Const COLOR_SCHEME_DEFAULT As String = "X11"
Public Const COLOR_SCHEME_PREFIX As String = "CS_"
Public Const COLOR_SCHEME_SVG As String = "SVG"
Public Const COLOR_SCHEME_X11 As String = "X11"

' Color constants
Public Const COLOR_BLACK As String = "black"
Public Const COLOR_WHITE As String = "white"

' Settings Cell Names
Public Const SETTINGS_APPEND_OPTIONS As String = "AppendOptions"
Public Const SETTINGS_APPEND_CONSOLE As String = "AppendConsole"
Public Const SETTINGS_APPEND_TIMESTAMP As String = "AppendTimestamp"
Public Const SETTINGS_BLANK_EDGE_LABELS As String = "BlankEdgeLabels"
Public Const SETTINGS_BLANK_NODE_LABELS As String = "BlankNodeLabels"
Public Const SETTINGS_COMMAND_LINE_PARAMETERS As String = "commandLineParameters"
Public Const SETTINGS_DEBUG As String = "Debug"
Public Const SETTINGS_EDGE_HEAD_LABELS As String = "EdgeHeadLabels"
Public Const SETTINGS_EDGE_LABELS As String = "EdgeLabels"
Public Const SETTINGS_EDGE_PORTS As String = "EdgePorts"
Public Const SETTINGS_EDGE_TAIL_LABELS As String = "EdgeTailLabels"
Public Const SETTINGS_EDGE_XLABELS As String = "EdgeXLabels"
Public Const SETTINGS_FILE_DISPOSITION As String = "FileDisposition"
Public Const SETTINGS_FILE_FORMAT As String = "FileFormat"
Public Const SETTINGS_FILE_NAME As String = "FileName"
Public Const SETTINGS_GRAPH_CENTER As String = "GraphCenter"
Public Const SETTINGS_GRAPH_CLUSTER_RANK As String = "GraphClusterRank"
Public Const SETTINGS_GRAPH_COMPOUND As String = "GraphCompound"
Public Const SETTINGS_GRAPH_CONCENTRATE As String = "GraphConcentrate"
Public Const SETTINGS_GRAPH_DIM As String = "GraphDim"
Public Const SETTINGS_GRAPH_DIMEN As String = "GraphDimen"
Public Const SETTINGS_GRAPH_FORCE_LABELS As String = "GraphForceLabels"
Public Const SETTINGS_GRAPH_INCLUDE_IMAGE_PATH As String = "GraphIncludeImagePath"
Public Const SETTINGS_GRAPH_MODE As String = "GraphMode"
Public Const SETTINGS_GRAPH_MODEL As String = "GraphModel"
Public Const SETTINGS_GRAPH_NEWRANK As String = "GraphNewrank"
Public Const SETTINGS_GRAPH_OPTIONS As String = "GraphOptions"
Public Const SETTINGS_GRAPH_ORDERING As String = "GraphOrdering"
Public Const SETTINGS_GRAPH_ORIENTATION As String = "GraphOrientation"
Public Const SETTINGS_GRAPH_OUTPUT_ORDER As String = "GraphOutputOrder"
Public Const SETTINGS_GRAPH_OVERLAP As String = "GraphOverlap"
Public Const SETTINGS_GRAPH_SMOOTHING As String = "GraphSmoothing"
Public Const SETTINGS_GRAPH_STRICT As String = "GraphStrict"
Public Const SETTINGS_GRAPH_TRANSPARENT As String = "GraphTransparent"
Public Const SETTINGS_GRAPH_TYPE As String = "GraphType"
Public Const SETTINGS_GRAPHVIZ_ENGINE As String = "GraphvizEngine"
Public Const SETTINGS_GRAPHVIZ_VERBOSE As String = "GraphvizVerbose"
Public Const SETTINGS_GV_PATH As String = "GV_PATH"
Public Const SETTINGS_HELP_ATTRIBUTES As String = "HelpAttributes"
Public Const SETTINGS_HELP_COLORS As String = "HelpColors"
Public Const SETTINGS_HELP_SHAPES As String = "HelpShapes"
Public Const SETTINGS_IMAGE_PATH As String = "ImagePath"
Public Const SETTINGS_IMAGE_TYPE As String = "ImageType"
Public Const SETTINGS_IMAGE_WORKSHEET As String = "ImageWorksheet"
Public Const SETTINGS_INCLUDE_EXTRA_ATTRIBUTES As String = "IncludeExtraAttributes"
Public Const SETTINGS_INCLUDE_STYLE_FORMAT As String = "IncludeStyleFormat"
Public Const SETTINGS_LANGUAGE As String = "Language"
Public Const SETTINGS_LOG_TO_CONSOLE As String = "LogToConsole"
Public Const SETTINGS_NODE_LABELS As String = "NodeLabels"
Public Const SETTINGS_NODE_XLABELS As String = "NodeXLabels"
Public Const SETTINGS_NODES_WITHOUT_RELATIONSHIPS As String = "NodesWithoutRelationships"
Public Const SETTINGS_OUTPUT_DIRECTORY As String = "OutputDirectory"
Public Const SETTINGS_PICTURE_NAME As String = "PictureName"
Public Const SETTINGS_POST_PROCESS_SVG As String = "PostProcessSVG"
Public Const SETTINGS_RANKDIR As String = "Rankdir"
Public Const SETTINGS_RELATIONSHIPS_WITHOUT_NODES As String = "RelationshipsWithoutNodes"
Public Const SETTINGS_RUN_MODE As String = "RunMode"
Public Const SETTINGS_SCALE_IMAGE As String = "ScaleImage"
Public Const SETTINGS_SPLINES As String = "Splines"
Public Const SETTINGS_VIEW_NAME As String = "ViewName"
Public Const SETTINGS_YES_NO_SWITCH_COLUMN As String = "YesNoSwitchColumn"

Public Const SETTINGS_EXCHANGE_DATA_EXPORT_ROW As String = "ExchangeDataExportRow"
Public Const SETTINGS_EXCHANGE_DATA_EXPORT_HEIGHT As String = "ExchangeDataExportHeight"
Public Const SETTINGS_EXCHANGE_DATA_EXPORT_VISIBLE As String = "ExchangeDataExportVisible"
Public Const SETTINGS_EXCHANGE_DATA_IMPORT_ACTION As String = "ExchangeDataImportAction"

Public Const SETTINGS_EXCHANGE_STYLES_EXPORT_ROW As String = "ExchangeStylesExportRow"
Public Const SETTINGS_EXCHANGE_STYLES_EXPORT_HEIGHT As String = "ExchangeStylesExportHeight"
Public Const SETTINGS_EXCHANGE_STYLES_EXPORT_VISIBLE As String = "ExchangeStylesExportVisible"
Public Const SETTINGS_EXCHANGE_STYLES_IMPORT_ACTION As String = "ExchangeStylesImportAction"

Public Const SETTINGS_EXCHANGE_SQL_EXPORT_ROW As String = "ExchangeSqlExportRow"
Public Const SETTINGS_EXCHANGE_SQL_EXPORT_HEIGHT As String = "ExchangeSqlExportHeight"
Public Const SETTINGS_EXCHANGE_SQL_EXPORT_VISIBLE As String = "ExchangeSqlExportVisible"
Public Const SETTINGS_EXCHANGE_SQL_IMPORT_ACTION As String = "ExchangeSqlImportAction"

Public Const SETTINGS_EXCHANGE_SVG_EXPORT_ROW As String = "ExchangeSvgExportRow"
Public Const SETTINGS_EXCHANGE_SVG_EXPORT_HEIGHT As String = "ExchangeSvgExportHeight"
Public Const SETTINGS_EXCHANGE_SVG_EXPORT_VISIBLE As String = "ExchangeSvgExportVisible"
Public Const SETTINGS_EXCHANGE_SVG_IMPORT_ACTION As String = "ExchangeSvgImportAction"

Public Const SETTINGS_DATA_SHOW_COMMENT As String = "ShowComment"
Public Const SETTINGS_DATA_SHOW_ITEM As String = "ShowItem"
Public Const SETTINGS_DATA_SHOW_LABEL As String = "ShowLabel"
Public Const SETTINGS_DATA_SHOW_OUTSIDE_LABEL As String = "ShowOutsideLabel"
Public Const SETTINGS_DATA_SHOW_TAIL_LABEL As String = "ShowTailLabel"
Public Const SETTINGS_DATA_SHOW_HEAD_LABEL As String = "ShowHeadLabel"
Public Const SETTINGS_DATA_SHOW_IS_RELATED_TO_ITEM As String = "ShowIsRelatedToItem"
Public Const SETTINGS_DATA_SHOW_STYLE As String = "ShowStyle"
Public Const SETTINGS_DATA_SHOW_EXTRA_STYLE_ATTRIBUTES As String = "ShowExtraStyleAttributes"
Public Const SETTINGS_DATA_SHOW_MESSAGES As String = "ShowMessages"

Public Const SETTINGS_EXT_TAB_NAME As String = "ExtTabName"
Public Const SETTINGS_EXT_TAB_GROUP_NAME_WEB As String = "ExtTabGroupNameWeb"
Public Const SETTINGS_EXT_TAB_GROUP_NAME_CODE As String = "ExtTabGroupNameCode"

Public Const SETTINGS_TAB_EXCHANGE As String = "SettingsExchangeTab"
Public Const SETTINGS_TAB_GRAPHVIZ As String = "SettingsGraphvizTab"
Public Const SETTINGS_TAB_SOURCE As String = "SettingsSourceTab"

' Style Designer worksheet cell names
Public Const DESIGNER_ADD_CAPTION As String = "AddCaption"
Public Const DESIGNER_BORDER_COLOR As String = "BorderColor"
Public Const DESIGNER_BORDER_PEN_WIDTH As String = "BorderPenWidth"
Public Const DESIGNER_BORDER_PERIPHERIES As String = "BorderPeripheries"
Public Const DESIGNER_BORDER_STYLE1 As String = "BorderStyle1"
Public Const DESIGNER_BORDER_STYLE2 As String = "BorderStyle2"
Public Const DESIGNER_BORDER_STYLE3 As String = "BorderStyle3"
Public Const DESIGNER_COLOR_SCHEME As String = "ColorScheme"
Public Const DESIGNER_EDGE_ARROW_HEAD_1 As String = "EdgeArrowHead1"
Public Const DESIGNER_EDGE_ARROW_HEAD_2 As String = "EdgeArrowHead2"
Public Const DESIGNER_EDGE_ARROW_HEAD_3 As String = "EdgeArrowHead3"
Public Const DESIGNER_EDGE_ARROW_SIZE As String = "EdgeArrowSize"
Public Const DESIGNER_EDGE_ARROW_TAIL_1 As String = "EdgeArrowTail1"
Public Const DESIGNER_EDGE_ARROW_TAIL_2 As String = "EdgeArrowTail2"
Public Const DESIGNER_EDGE_ARROW_TAIL_3 As String = "EdgeArrowTail3"
Public Const DESIGNER_EDGE_COLOR_1 As String = "EdgeColor1"
Public Const DESIGNER_EDGE_COLOR_2 As String = "EdgeColor2"
Public Const DESIGNER_EDGE_COLOR_3 As String = "EdgeColor3"
Public Const DESIGNER_EDGE_DECORATE As String = "EdgeDecorate"
Public Const DESIGNER_EDGE_DIRECTION As String = "EdgeDirection"
Public Const DESIGNER_EDGE_HEAD_CLIP As String = "EdgeHeadClip"
Public Const DESIGNER_EDGE_HEAD_PORT As String = "EdgeHeadPort"
Public Const DESIGNER_EDGE_LABEL_ANGLE As String = "EdgeLabelAngle"
Public Const DESIGNER_EDGE_LABEL_DISTANCE As String = "EdgeLabelDistance"
Public Const DESIGNER_EDGE_LABEL_FLOAT As String = "EdgeLabelFloat"
Public Const DESIGNER_EDGE_LABEL_FONT_COLOR As String = "EdgeLabelFontColor"
Public Const DESIGNER_EDGE_LABEL_FONT_NAME As String = "EdgeLabelFontName"
Public Const DESIGNER_EDGE_LABEL_FONT_SIZE As String = "EdgeLabelFontSize"
Public Const DESIGNER_EDGE_PEN_WIDTH As String = "EdgePenWidth"
Public Const DESIGNER_EDGE_STYLE As String = "EdgeStyle"
Public Const DESIGNER_EDGE_TAIL_CLIP As String = "EdgeTailClip"
Public Const DESIGNER_EDGE_TAIL_PORT As String = "EdgeTailPort"
Public Const DESIGNER_EDGE_WEIGHT As String = "EdgeWeight"
Public Const DESIGNER_FILL_COLOR As String = "FillColor"
Public Const DESIGNER_FONT_BOLD As String = "FontBold"
Public Const DESIGNER_FONT_COLOR As String = "FontColor"
Public Const DESIGNER_FONT_ITALIC As String = "FontItalic"
Public Const DESIGNER_FONT_NAME As String = "FontName"
Public Const DESIGNER_FONT_SIZE As String = "FontSize"
Public Const DESIGNER_FORMAT_STRING As String = "FormatString"
Public Const DESIGNER_GRADIENT_FILL_ANGLE As String = "GradientFillAngle"
Public Const DESIGNER_GRADIENT_FILL_COLOR As String = "GradientFillColor"
Public Const DESIGNER_GRADIENT_FILL_TYPE As String = "GradientFillType"
Public Const DESIGNER_GRADIENT_FILL_WEIGHT As String = "GradientFillWeight"
Public Const DESIGNER_HEAD_LABEL_TEXT As String = "HeadLabelText"
Public Const DESIGNER_LABEL_JUSTIFICATION As String = "LabelJustification"
Public Const DESIGNER_LABEL_LOCATION As String = "LabelLocation"
Public Const DESIGNER_LABEL_TEXT As String = "LabelText"
Public Const DESIGNER_MODE As String = "StyleDesignerMode"
Public Const DESIGNER_NODE_DISTORTION As String = "NodeDistortion"
Public Const DESIGNER_NODE_FIXED_SIZE As String = "NodeFixedSize"
Public Const DESIGNER_NODE_HEIGHT As String = "NodeHeight"
Public Const DESIGNER_NODE_IMAGE_NAME As String = "NodeImageName"
Public Const DESIGNER_NODE_IMAGE_POSITION As String = "NodeImagePosition"
Public Const DESIGNER_NODE_IMAGE_SCALE As String = "NodeImageScale"
Public Const DESIGNER_NODE_METRIC As String = "NodeMetric"
Public Const DESIGNER_NODE_ORIENTATION As String = "NodeOrientation"
Public Const DESIGNER_NODE_REGULAR As String = "NodeRegular"
Public Const DESIGNER_NODE_SHAPE As String = "NodeShape"
Public Const DESIGNER_NODE_SIDES As String = "NodeSides"
Public Const DESIGNER_NODE_SKEW As String = "NodeSkew"
Public Const DESIGNER_NODE_WIDTH As String = "NodeWidth"
Public Const DESIGNER_PREVIEW_CELL As String = "DesignerPreviewCell"
Public Const DESIGNER_TAIL_LABEL_TEXT As String = "TailLabelText"
Public Const DESIGNER_XLABEL_TEXT As String = "XlabelText"

Public Const DESIGNER_CLUSTER_MARGIN As String = "ClusterMargin"
Public Const DESIGNER_CLUSTER_PACKMODE As String = "ClusterPackmode"
Public Const DESIGNER_CLUSTER_ARRAY_MAJOR As String = "ClusterArrayMajor"
Public Const DESIGNER_CLUSTER_ARRAY_SPLIT As String = "ClusterArraySplit"
Public Const DESIGNER_CLUSTER_ARRAY_ALIGN As String = "ClusterArrayAlign"
Public Const DESIGNER_CLUSTER_ARRAY_JUSTIFY As String = "ClusterArrayJustify"
Public Const DESIGNER_CLUSTER_ARRAY_SORT As String = "ClusterArraySort"


' Default settings
Public Const SETTINGS_DEFAULT_TO_WORKSHEET_TYPE As String = "png"
Public Const SETTINGS_DEFAULT_TO_FILE_TYPE As String = "pdf"
Public Const SETTINGS_DEFAULT_GRAPHVIZ_ENGINE As String = "dot"

' Worksheet row and column mapping of cell names on the 'data' worksheet
Public Const SETTINGS_DATA_ROW_HEADING As String = "DataRowHeading"
Public Const SETTINGS_DATA_ROW_FIRST As String = "DataRowFirst"
Public Const SETTINGS_DATA_ROW_LAST As String = "DataRowLast"
Public Const SETTINGS_DATA_COL_COMMENT As String = "DataColComment"
Public Const SETTINGS_DATA_COL_STYLE As String = "DataColStyle"
Public Const SETTINGS_DATA_COL_ITEM As String = "DataColItem"
Public Const SETTINGS_DATA_COL_LABEL As String = "DataColLabel"
Public Const SETTINGS_DATA_COL_LABEL_X As String = "DataColXLabel"
Public Const SETTINGS_DATA_COL_LABEL_TAIL As String = "DataColTailLabel"
Public Const SETTINGS_DATA_COL_LABEL_HEAD As String = "DataColHeadLabel"
Public Const SETTINGS_DATA_COL_TOOLTIP As String = "DataColTooltip"
Public Const SETTINGS_DATA_COL_IS_RELATED_TO As String = "DataColIsRelatedTo"
Public Const SETTINGS_DATA_COL_EXTRA_ATTRIBUTES As String = "DataColExtraAttrs"
Public Const SETTINGS_DATA_COL_ERROR_MESSAGES As String = "DataColErrMessage"
Public Const SETTINGS_DATA_COL_GRAPH As String = "DataColGraph"

' Worksheet row and column mapping of cell names on the 'source' worksheet
Public Const SETTINGS_SOURCE_ROW_HEADING As String = "SourceRowHeading"
Public Const SETTINGS_SOURCE_ROW_FIRST As String = "SourceRowFirst"

Public Const SETTINGS_SOURCE_COL_LINE_NUMBER As String = "SourceColLineNumber"
Public Const SETTINGS_SOURCE_COL_SOURCE As String = "SourceColSource"
Public Const SETTINGS_SOURCE_INDENT As String = "SourceIndent"

' Worksheet row and column mapping of cell names on the 'styles' worksheet
Public Const SETTINGS_STYLES_ROW_FIRST As String = "StylesRowFirst"
Public Const SETTINGS_STYLES_ROW_LAST As String = "StylesRowLast"
Public Const SETTINGS_STYLES_ROW_HEADING As String = "StylesRowHeading"
Public Const SETTINGS_STYLES_COL_SHOW_STYLE As String = "StylesColShowStyle"
Public Const SETTINGS_STYLES_COL_COMMENT As String = "StylesColComment"
Public Const SETTINGS_STYLES_COL_STYLE As String = "StylesColStyle"
Public Const SETTINGS_STYLES_COL_FORMAT As String = "StylesColFormat"
Public Const SETTINGS_STYLES_COL_OBJECT_TYPE As String = "StylesColObjType"
Public Const SETTINGS_STYLES_COL_FIRST_YES_NO_VIEW As String = "StylesColFirstYesNoView"
Public Const SETTINGS_STYLES_SUFFIX_OPEN As String = "StylesSuffixOpen"
Public Const SETTINGS_STYLES_SUFFIX_CLOSE As String = "StylesSuffixClose"

' Worksheet row and column mapping of cell names on the 'sql' worksheet
Public Const SETTINGS_SQL_ROW_HEADING As String = "SqlRowHeading"
Public Const SETTINGS_SQL_ROW_FIRST As String = "SqlRowFirst"

Public Const SETTINGS_SQL_COL_COMMENT As String = "SqlColComment"
Public Const SETTINGS_SQL_COL_SQL_STATEMENT As String = "SqlColSqlStatement"
Public Const SETTINGS_SQL_COL_EXCEL_FILE As String = "SqlColExcelFile"
Public Const SETTINGS_SQL_COL_STATUS As String = "SqlColStatus"
Public Const SETTINGS_SQL_COL_FILTER As String = "SqlColFilter"
Public Const SETTINGS_SQL_FILTER_VALUE As String = "SqlFilterValue"

Public Const SETTINGS_SQL_COUNT_PLACEHOLDER_CLUSTER As String = "SqlCountPlaceholderCluster"
Public Const SETTINGS_SQL_COUNT_PLACEHOLDER_SUBCLUSTER As String = "SqlCountPlaceholderSubcluster"
Public Const SETTINGS_SQL_COUNT_PLACEHOLDER_RECORDSET As String = "SqlCountPlaceholderRecordset"

Public Const SETTINGS_SQL_FIELD_NAME_CLUSTER As String = "SqlFieldNameCluster"
Public Const SETTINGS_SQL_FIELD_NAME_CLUSTER_LABEL As String = "SqlFieldNameClusterLabel"
Public Const SETTINGS_SQL_FIELD_NAME_CLUSTER_STYLE_NAME As String = "SqlFieldNameClusterStyleName"
Public Const SETTINGS_SQL_FIELD_NAME_CLUSTER_ATTRIBUTES As String = "SqlFieldNameClusterAttributes"
Public Const SETTINGS_SQL_FIELD_NAME_CLUSTER_TOOLTIP As String = "SqlFieldNameClusterTooltip"

Public Const SETTINGS_SQL_FIELD_NAME_SUBCLUSTER As String = "SqlFieldNameSubcluster"
Public Const SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_LABEL As String = "SqlFieldNameSubclusterLabel"
Public Const SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_STYLE_NAME As String = "SqlFieldNameSubclusterStyleName"
Public Const SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_ATTRIBUTES As String = "SqlFieldNameSubclusterAttributes"
Public Const SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_TOOLTIP As String = "SqlFieldNameSubclusterTooltip"

Public Const SETTINGS_SQL_FIELD_NAME_SPLIT_LENGTH As String = "SqlFieldNameSplitLength"
Public Const SETTINGS_SQL_FIELD_NAME_LINE_ENDING As String = "SqlFieldNameLineEnding"

' Controls what to import/export
Public Const SETTINGS_TOOLS_EXCHANGE_DATA_WORKSHEET As String = "ExchangeDataWorksheet"
Public Const SETTINGS_TOOLS_EXCHANGE_STYLES_WORKSHEET As String = "ExchangeStylesWorksheet"
Public Const SETTINGS_TOOLS_EXCHANGE_SQL_WORKSHEET As String = "ExchangeSqlWorksheet"
Public Const SETTINGS_TOOLS_EXCHANGE_SVG_WORKSHEET As String = "ExchangeSvgWorksheet"
Public Const SETTINGS_TOOLS_EXCHANGE_GRAPH_OPTIONS As String = "ExchangeGraphOptions"
Public Const SETTINGS_TOOLS_EXCHANGE_WORKSHEET_LAYOUTS As String = "ExchangeWorksheetLayouts"
Public Const SETTINGS_TOOLS_EXCHANGE_METADATA As String = "ExchangeMetadata"

' Controls which worksheets to show/hide
Public Const SETTINGS_TOOLS_TOGGLE_ABOUT As String = "ToggleAbout"
Public Const SETTINGS_TOOLS_TOGGLE_CONSOLE As String = "ToggleConsole"
Public Const SETTINGS_TOOLS_TOGGLE_DIAGNOSTICS As String = "ToggleDiagnostics"
Public Const SETTINGS_TOOLS_TOGGLE_LISTS As String = "ToggleLists"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_DE_DE As String = "locale_de_DE"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_EN_GB As String = "locale_en_GB"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_EN_US As String = "locale_en_US"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_FR_FR As String = "locale_fr_FR"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_IT_IT As String = "locale_it_IT"
Public Const SETTINGS_TOOLS_TOGGLE_LOCALE_PL_PL As String = "locale_pl_PL"
Public Const SETTINGS_TOOLS_TOGGLE_SETTINGS As String = "ToggleSettings"
Public Const SETTINGS_TOOLS_TOGGLE_SOURCE As String = "ToggleSource"
Public Const SETTINGS_TOOLS_TOGGLE_SQL As String = "ToggleSql"
Public Const SETTINGS_TOOLS_TOGGLE_STYLE_DESIGNER As String = "ToggleStyleDesigner"
Public Const SETTINGS_TOOLS_TOGGLE_STYLES As String = "ToggleStyles"
Public Const SETTINGS_TOOLS_TOGGLE_SVG As String = "ToggleSvg"

' Controls which tabs without worksheets to show/hide
Public Const SETTINGS_TABS_TOGGLE_EXCHANGE As String = "ToggleExchange"

' Names of Named Range lists used as dropdown values
Public Const LISTS_FONT_SIZES As String = "FontSizes"
#If Mac Then
Public Const LISTS_FONTS As String = "Fonts"
#End If
Public Const LISTS_IMAGE_SCALE As String = "ImageScale"

Public Const RANGE_STYLE_NAMES As String = "StyleNames"

' Ribbon constants (control ids and group ids)
Public Const RIBBON_CTL_ALIGN_BOTTOM As String = "alignBottom"
Public Const RIBBON_CTL_ALIGN_TOP As String = "alignTop"
Public Const RIBBON_CTL_BORDER_COLOR As String = "borderColor"
Public Const RIBBON_CTL_BORDER_PERIPHERIES As String = "borderPeripheries"
Public Const RIBBON_CTL_BORDER_STYLE2 As String = "borderStyle2"
Public Const RIBBON_CTL_BORDER_STYLE3 As String = "borderStyle3"
Public Const RIBBON_CTL_COLOR_SCHEME As String = "colorScheme"
Public Const RIBBON_CTL_COMPOUND As String = "compound"
Public Const RIBBON_CTL_COPY_TO_CLIPBOARD As String = "copyToClipboard"
Public Const RIBBON_CTL_CURRENT_COLOR_SCHEME As String = "currentColorScheme"
Public Const RIBBON_CTL_DESIGN_MODE_CLUSTER As String = "designModeCluster"
Public Const RIBBON_CTL_DESIGN_MODE_EDGE As String = "designModeEdge"
Public Const RIBBON_CTL_DESIGN_MODE_NODE As String = "designModeNode"
Public Const RIBBON_CTL_DIRECTED As String = "directed"
Public Const RIBBON_CTL_EDGE_ARROW_HEAD1 As String = "edgeArrowHead1"
Public Const RIBBON_CTL_EDGE_ARROW_HEAD2 As String = "edgeArrowHead2"
Public Const RIBBON_CTL_EDGE_ARROW_HEAD3 As String = "edgeArrowHead3"
Public Const RIBBON_CTL_EDGE_ARROW_SIZE As String = "edgeArrowSize"
Public Const RIBBON_CTL_EDGE_ARROW_TAIL1 As String = "edgeArrowTail1"
Public Const RIBBON_CTL_EDGE_ARROW_TAIL2 As String = "edgeArrowTail2"
Public Const RIBBON_CTL_EDGE_ARROW_TAIL3 As String = "edgeArrowTail3"
Public Const RIBBON_CTL_EDGE_COLOR1 As String = "edgeColor1"
Public Const RIBBON_CTL_EDGE_COLOR2 As String = "edgeColor2"
Public Const RIBBON_CTL_EDGE_COLOR3 As String = "edgeColor3"
Public Const RIBBON_CTL_EDGE_DIRECTION As String = "edgeDirection"
Public Const RIBBON_CTL_EDGE_LABEL_ANGLE As String = "edgeLabelAngle"
Public Const RIBBON_CTL_EDGE_LABEL_DECORATE As String = "edgeLabelDecorate"
Public Const RIBBON_CTL_EDGE_LABEL_DISTANCE As String = "edgeLabelDistance"
Public Const RIBBON_CTL_EDGE_LABEL_FLOAT As String = "edgeLabelFloat"
Public Const RIBBON_CTL_EDGE_LABEL_FONT_COLOR As String = "labelFontColor"
Public Const RIBBON_CTL_LABEL_FONT_NAME As String = "labelFontName"
Public Const RIBBON_CTL_EDGE_LABELS_BLANK As String = "blankEdgeLabels"
Public Const RIBBON_CTL_EDGE_LABELS_DEFAULT As String = "defaultEdgeLabels"
Public Const RIBBON_CTL_FILL_COLOR As String = "fillColor"
Public Const RIBBON_CTL_FONT_COLOR As String = "fontColor"
Public Const RIBBON_CTL_GRADIENT_FILL_ANGLE As String = "gradientFillAngle"
Public Const RIBBON_CTL_GRADIENT_FILL_COLOR As String = "gradientFillColor"
Public Const RIBBON_CTL_GRADIENT_FILL_TYPE As String = "gradientFillType"
Public Const RIBBON_CTL_GRADIENT_FILL_WEIGHT As String = "gradientFillWeight"
Public Const RIBBON_CTL_GRAPH_CLUSTER_RANK As String = "clusterrank"
Public Const RIBBON_CTL_GRAPH_DIM As String = "dim"
Public Const RIBBON_CTL_GRAPH_DIMEN As String = "dimen"
Public Const RIBBON_CTL_GRAPH_MODE As String = "mode"
Public Const RIBBON_CTL_GRAPH_MODEL As String = "model"
Public Const RIBBON_CTL_GRAPH_ORDERING As String = "ordering"
Public Const RIBBON_CTL_GRAPH_OUTPUT_ORDER As String = "outputorder"
Public Const RIBBON_CTL_GRAPH_OVERLAP As String = "overlap"
Public Const RIBBON_CTL_GRAPH_OVERLAP_MENU As String = "overlapMenu"
Public Const RIBBON_CTL_GRAPH_SMOOTHING As String = "smoothing"
Public Const RIBBON_CTL_IMPORT_DATA_ROW_APPEND As String = "importDataRowAppend"
Public Const RIBBON_CTL_IMPORT_DATA_ROW_REPLACE As String = "importDataRowReplace"
Public Const RIBBON_CTL_IMPORT_SQL_ROW_APPEND As String = "importSqlRowAppend"
Public Const RIBBON_CTL_IMPORT_SQL_ROW_REPLACE As String = "importSqlRowReplace"
Public Const RIBBON_CTL_IMPORT_STYLES_ROW_APPEND As String = "importStylesRowAppend"
Public Const RIBBON_CTL_IMPORT_STYLES_ROW_REPLACE As String = "importStylesRowReplace"
Public Const RIBBON_CTL_IMPORT_SVG_ROW_APPEND As String = "importSvgRowAppend"
Public Const RIBBON_CTL_IMPORT_SVG_ROW_REPLACE As String = "importSvgRowReplace"
Public Const RIBBON_CTL_JUSTIFY_LEFT As String = "justifyLeft"
Public Const RIBBON_CTL_JUSTIFY_RIGHT As String = "justifyRight"
Public Const RIBBON_CTL_LABEL_JUSTIFICATION As String = "labelJustification"
Public Const RIBBON_CTL_LABEL_STYLE_SEPARATOR As String = "labelStyleSeparator"
Public Const RIBBON_CTL_LAYOUT_DIRECTION As String = "layoutDirection"
Public Const RIBBON_CTL_NEWRANK As String = "newrank"
Public Const RIBBON_CTL_NODE_DISTORTION As String = "nodeDistortion"
Public Const RIBBON_CTL_NODE_HEIGHT As String = "nodeHeight"
Public Const RIBBON_CTL_NODE_HEIGHT_METRIC As String = "nodeHeightMetric"
Public Const RIBBON_CTL_NODE_IMAGE_NAME As String = "nodeImageName"
Public Const RIBBON_CTL_NODE_IMAGE_POSITION As String = "nodeImagePosition"
Public Const RIBBON_CTL_NODE_IMAGE_POS_SEPARATOR As String = "imagePosSeparator"
Public Const RIBBON_CTL_NODE_IMAGE_SCALE As String = "nodeImageScale"
Public Const RIBBON_CTL_NODE_LABELS_BLANK As String = "blankNodeLabels"
Public Const RIBBON_CTL_NODE_LABELS_DEFAULT As String = "defaultNodeLabels"
Public Const RIBBON_CTL_NODE_REGULAR As String = "nodeRegular"
Public Const RIBBON_CTL_NODE_ROTATION As String = "nodeRotation"
Public Const RIBBON_CTL_NODE_SHAPE As String = "nodeShape"
Public Const RIBBON_CTL_NODE_SIDES As String = "nodeSides"
Public Const RIBBON_CTL_NODE_SKEW As String = "nodeSkew"
Public Const RIBBON_CTL_NODE_WIDTH As String = "nodeWidth"
Public Const RIBBON_CTL_NODE_WIDTH_METRIC As String = "nodeWidthMetric"
Public Const RIBBON_CTL_POLYGON_SEPARATOR As String = "polygonSeparator"
Public Const RIBBON_CTL_SAVE_TO_STYLES_WORKSHEET As String = "saveToStylesWorksheet"
Public Const RIBBON_CTL_SHOW_COMMENT As String = "ShowComment"
Public Const RIBBON_CTL_SHOW_EXTRA_STYLE_ATTRIBUTES As String = "ShowExtraStyleAttributes"
Public Const RIBBON_CTL_SHOW_HEAD_LABEL As String = "ShowHeadLabel"
Public Const RIBBON_CTL_SHOW_IS_RELATED_TO_ITEM As String = "ShowIsRelatedToItem"
Public Const RIBBON_CTL_SHOW_ITEM As String = "ShowItem"
Public Const RIBBON_CTL_SHOW_LABEL As String = "ShowLabel"
Public Const RIBBON_CTL_SHOW_MESSAGES As String = "ShowMessages"
Public Const RIBBON_CTL_SHOW_OUTSIDE_LABEL As String = "ShowOutsideLabel"
Public Const RIBBON_CTL_SHOW_STYLE As String = "ShowStyle"
Public Const RIBBON_CTL_SHOW_TAIL_LABEL As String = "ShowTailLabel"
Public Const RIBBON_CTL_SHOW_TOOLTIP As String = "ShowTooltip"
Public Const RIBBON_CTL_SPLINES As String = "splines"
Public Const RIBBON_CTL_SQL_CLIPBOARD As String = "sqlClipboard"
Public Const RIBBON_CTL_SQL_EDIT_CELL As String = "sqlEditCell"
Public Const RIBBON_CTL_SVG_CLIPBOARD As String = "svgClipboard"
Public Const RIBBON_CTL_SVG_EDIT_CELL As String = "svgEditCell"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_SETTINGS As String = "toggleSettings"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_SOURCE As String = "toggleSource"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_SQL As String = "toggleSql"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_SVG As String = "toggleSvg"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_CONSOLE As String = "toggleConsole"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_LISTS As String = "toggleLists"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_ABOUT As String = "toggleAbout"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_DIAGNOSTICS As String = "toggleDiagnostics"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_STYLE_DESIGNER As String = "toggleStyleDesigner"
'Public Const RIBBON_CTL_TOOLS_TOGGLE_STYLES As String = "toggleStyles"

Public Const RIBBON_CTL_ARRAY_ALIGN_TOP As String = "arrayAlignTop"
Public Const RIBBON_CTL_ARRAY_ALIGN_BOTTOM As String = "arrayAlignBottom"
Public Const RIBBON_CTL_ARRAY_JUSTIFY_LEFT As String = "arrayJustifyLeft"
Public Const RIBBON_CTL_ARRAY_JUSTIFY_RIGHT As String = "arrayJustifyRight"
Public Const RIBBON_CTL_ARRAY_MAJOR As String = "arrayMajor"
Public Const RIBBON_CTL_ARRAY_SPLIT As String = "arraySplit"
Public Const RIBBON_CTL_ARRAY_SORT As String = "arraySort"
Public Const RIBBON_CTL_ARRAY_SEPARATOR As String = "arraySeparator"
Public Const RIBBON_CTL_PACK_SEPARATOR As String = "packSeparator"
Public Const RIBBON_CTL_CLUSTER_PACK As String = "clusterPack"
Public Const RIBBON_CTL_CLUSTER_MARGIN As String = "clusterMargin"
Public Const RIBBON_CTL_CLUSTER_MARGIN_MM As String = "clusterMarginMM"
Public Const RIBBON_CTL_CLUSTER_PACKMODE As String = "clusterPackmode"

Public Const RIBBON_GRP_BORDERS As String = "designerGroupBorders"
Public Const RIBBON_GRP_EDGE_ARROW As String = "designerGroupEdgeArrow"
Public Const RIBBON_GRP_EDGE_ARROW_HEAD As String = "designerGroupEdgeArrowHead"
Public Const RIBBON_GRP_EDGE_ARROW_TAIL As String = "designerGroupEdgeArrowTail"
Public Const RIBBON_GRP_EDGE_COLORS As String = "designerGroupEdgeColors"
Public Const RIBBON_GRP_EDGE_HEAD_TAIL As String = "designerGroupHeadTail"
Public Const RIBBON_GRP_EDGE_STYLE As String = "designerGroupEdgeStyle"
Public Const RIBBON_GRP_FILL_COLOR As String = "designerGroupFillColor"
Public Const RIBBON_GRP_GRADIENT_FILL_COLOR As String = "designerGroupGradientFillColor"
Public Const RIBBON_GRP_LABELS As String = "designerGroupLabels"
Public Const RIBBON_GRP_NODE_DIMENSIONS As String = "designerGroupNodeDimensions"
Public Const RIBBON_GRP_NODE_IMAGE As String = "designerGroupNodeImage"
Public Const RIBBON_GRP_NODE_SHAPE As String = "designerGroupNodeShape"
Public Const RIBBON_GRP_PACK As String = "designerGroupPack"

Public Const RIBBON_TAB_ABOUT As String = "aboutTab"
Public Const RIBBON_TAB_GRAPHVIZ As String = "graphvizTab"
Public Const RIBBON_TAB_STYLE_DESIGNER As String = "styleDesignerTab"
Public Const RIBBON_TAB_SOURCE As String = "sourceTab"
Public Const RIBBON_TAB_SQL As String = "sqlTab"
Public Const RIBBON_TAB_SVG As String = "svgTab"
Public Const RIBBON_TAB_CONSOLE As String = "consoleTab"
Public Const RIBBON_TAB_DIAGNOSTICS As String = "diagnosticsTab"
Public Const RIBBON_TAB_EXCHANGE As String = "toolsTab"
Public Const RIBBON_TAB_WORKSHEETS As String = "worksheetsTab"
Public Const RIBBON_TAB_STYLES As String = "stylesTab"

Public Const RIBBON_LOCALE_PREFIX As String = "locale_"

' json file exchange constants
Public Const JSON_COLUMN As String = "column"
Public Const JSON_COLUMNS As String = "columns"
Public Const JSON_ENABLED As String = "enabled"
Public Const JSON_FIRST As String = "first"
Public Const JSON_HEADING As String = "heading"
Public Const JSON_HEIGHT As String = "height"
Public Const JSON_HIDDEN As String = "hidden"
Public Const JSON_ID As String = "id"
Public Const JSON_RANGES As String = "ranges"
Public Const JSON_ROW As String = "row"
Public Const JSON_ROWS As String = "rows"
Public Const JSON_WIDTH As String = "width"
Public Const JSON_WRAP_TEXT As String = "wrapText"
Public Const JSON_ZOOM As String = "zoom"

Public Const JSON_DATA_EXTRA_ATTRIBUTES As String = "extraAttributes"
Public Const JSON_DATA_FLAG As String = "flag"
Public Const JSON_DATA_GRAPH_DISPLAY_COLUMN As String = "graphDisplayColumn"
Public Const JSON_DATA_HEAD_LABEL As String = "headLabel"
Public Const JSON_DATA_ITEM As String = "item"
Public Const JSON_DATA_LABEL As String = "label"
Public Const JSON_DATA_MESSAGE As String = "message"
Public Const JSON_DATA_OUTSIDE_LABEL As String = "outsideLabel"
Public Const JSON_DATA_RELATED_ITEM As String = "relatedItem"
Public Const JSON_DATA_STYLE_NAME As String = "styleName"
Public Const JSON_DATA_TAIL_LABEL As String = "tailLabel"
Public Const JSON_DATA_TOOLTIP As String = "tooltip"

Public Const JSON_STYLES_FLAG As String = "flag"
Public Const JSON_STYLES_NAME As String = "name"
Public Const JSON_STYLES_FORMAT As String = "format"
Public Const JSON_STYLES_TYPE As String = "type"
Public Const JSON_STYLES_VIEW As String = "view"
Public Const JSON_STYLES_VIEW_SWITCHES As String = "viewSwitches"

Public Const JSON_SQL_SQL_STATEMENT As String = "sqlStatement"
Public Const JSON_SQL_EXCEL_FILE As String = "excelFile"
Public Const JSON_SQL_STATUS As String = "status"
Public Const JSON_SQL_FILTERS As String = "filters"

Public Const JSON_SVG_FIND As String = "find"
Public Const JSON_SVG_REPLACE As String = "replace"

Public Const JSON_SOURCE_LINE_NUMBER As String = "lineNumber"
Public Const JSON_SOURCE_SOURCE As String = "source"

Public Const BUTTON_PREFIX_EXT_CODE As String = "ExtCode"
Public Const BUTTON_PREFIX_EXT_WEB As String = "ExtWeb"
Public Const BUTTON_PREFIX_SOURCE_WEB As String = "SourceWeb"
Public Const BUTTON_SUFFIX_SCREENTIP As String = "Screentip"
Public Const BUTTON_SUFFIX_SUB As String = "Sub"
Public Const BUTTON_SUFFIX_SUPERTIP As String = "Supertip"
Public Const BUTTON_SUFFIX_TEXT As String = "Text"
Public Const BUTTON_SUFFIX_URL As String = "URL"
Public Const BUTTON_SUFFIX_VISIBLE As String = "Visible"

Public Const JSON_SETTINGS_ADD_STRICT As String = "addStrict"
Public Const JSON_SETTINGS_APPEND_OPTIONS As String = "appendOptions"
Public Const JSON_SETTINGS_APPEND_TIME_STAMP As String = "appendTimeStamp"
Public Const JSON_SETTINGS_BLANK_EDGE_LABELS As String = "blankEdgeLabels"
Public Const JSON_SETTINGS_BLANK_NODE_LABELS As String = "blankNodeLabels"
Public Const JSON_SETTINGS_BUTTON_TEXT As String = "buttonText"
Public Const JSON_SETTINGS_BUTTONS As String = "buttons"
Public Const JSON_SETTINGS_CENTER As String = "center"
Public Const JSON_SETTINGS_CLUSTER_RANK As String = "clusterRank"
Public Const JSON_SETTINGS_COMMAND_LINE_PARAMETERS As String = "additionalCmdParameters"
Public Const JSON_SETTINGS_COMPOUND As String = "compound"
Public Const JSON_SETTINGS_CONCENTRATE As String = "concentrate"
Public Const JSON_SETTINGS_DEBUG_SWITCH As String = "debug"
Public Const JSON_SETTINGS_DIM As String = "dim"
Public Const JSON_SETTINGS_DIMEN As String = "dimen"
Public Const JSON_SETTINGS_DIRECTION As String = "direction"
Public Const JSON_SETTINGS_DIRECTORY As String = "directory"
Public Const JSON_SETTINGS_ENGINE As String = "engine"
Public Const JSON_SETTINGS_FILE_DISPOSITION As String = "fileDisposition"
Public Const JSON_SETTINGS_FILE_NAME_PREFIX As String = "fileNamePrefix"
Public Const JSON_SETTINGS_FORCE_LABELS As String = "forceLabels"
Public Const JSON_SETTINGS_GRAPH_OPTIONS As String = "additionalGraphOptions"
Public Const JSON_SETTINGS_GRAPH_TYPE As String = "graphType"
Public Const JSON_SETTINGS_GROUP_NAME As String = "groupName"
Public Const JSON_SETTINGS_GRAPHVIZ_VERBOSE As String = "graphvizVerbose"
Public Const JSON_SETTINGS_GV_PATH As String = "graphvizPath"
Public Const JSON_SETTINGS_IMAGE_PATH As String = "imagePath"
Public Const JSON_SETTINGS_IMAGE_TYPE As String = "imageType"
Public Const JSON_SETTINGS_IMAGE_WORKSHEET As String = "imageWorksheet"
Public Const JSON_SETTINGS_INCLUDE_EDGE_HEAD_LABELS As String = "includeEdgeHeadLabels"
Public Const JSON_SETTINGS_INCLUDE_EDGE_LABELS As String = "includeEdgeLabels"
Public Const JSON_SETTINGS_INCLUDE_EDGE_PORTS As String = "includeEdgePorts"
Public Const JSON_SETTINGS_INCLUDE_EDGE_TAIL_LABELS As String = "includeEdgeTailLabels"
Public Const JSON_SETTINGS_INCLUDE_EDGE_XLABELS As String = "includeEdgeXLabels"
Public Const JSON_SETTINGS_INCLUDE_EXTRA_ATTRIBUTES As String = "includeExtraAttributes"
Public Const JSON_SETTINGS_INCLUDE_IMAGE_PATH As String = "includeImagePath"
Public Const JSON_SETTINGS_INCLUDE_NODE_LABELS As String = "includeNodeLabels"
Public Const JSON_SETTINGS_INCLUDE_NODE_XLABELS As String = "includeNodeXLabels"
Public Const JSON_SETTINGS_INCLUDE_ORPHAN_EDGES As String = "includeOrphanEdges"
Public Const JSON_SETTINGS_INCLUDE_ORPHAN_NODES As String = "includeOrphanNodes"
Public Const JSON_SETTINGS_INCLUDE_STYLE_FORMAT As String = "includeStyleFormat"
Public Const JSON_SETTINGS_INDENT As String = "indent"
Public Const JSON_SETTINGS_LANGUAGE As String = "language"
Public Const JSON_SETTINGS_LOG_TO_CONSOLE As String = "logToConsole"
Public Const JSON_SETTINGS_APPEND_CONSOLE As String = "appendConsole"
Public Const JSON_SETTINGS_MODE As String = "mode"
Public Const JSON_SETTINGS_MODEL As String = "model"
Public Const JSON_SETTINGS_NEWRANK As String = "newrank"
Public Const JSON_SETTINGS_ORDERING As String = "ordering"
Public Const JSON_SETTINGS_ORIENTATION As String = "orientation"
Public Const JSON_SETTINGS_OUTPUT_ORDER As String = "outputOrder"
Public Const JSON_SETTINGS_OVERLAP As String = "overlap"
Public Const JSON_SETTINGS_PICTURE_NAME As String = "pictureName"
Public Const JSON_SETTINGS_RANKDIR As String = "rankdir"
Public Const JSON_SETTINGS_RUN_MODE As String = "runMode"
Public Const JSON_SETTINGS_SCALE_IMAGE As String = "scaleImage"
Public Const JSON_SETTINGS_SCREEN_TIP As String = "screenTip"
Public Const JSON_SETTINGS_SELECTED_VIEW_COLUMN As String = "selectedViewColumn"
Public Const JSON_SETTINGS_SMOOTHING As String = "smoothing"
Public Const JSON_SETTINGS_SPLINES As String = "splines"
Public Const JSON_SETTINGS_STYLES_SUFFIX_CLOSE As String = "suffixClose"
Public Const JSON_SETTINGS_STYLES_SUFFIX_OPEN As String = "suffixOpen"
Public Const JSON_SETTINGS_SUB As String = "subroutine"
Public Const JSON_SETTINGS_SUPER_TIP As String = "superTip"
Public Const JSON_SETTINGS_TRANSPARENT_BACKGROUND As String = "transparentBackground"
Public Const JSON_SETTINGS_URL As String = "url"
Public Const JSON_SETTINGS_VISIBLE As String = "visible"

Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER As String = "cluster"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER_LABEL As String = "clusterLabel"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER_STYLE_NAME As String = "clusterStyleName"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER_ATTRIBUTES As String = "clusterAttributes"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER_TOOLTIP As String = "clusterTooltip"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_CLUSTER_PLACEHOLDER As String = "clusterPlaceholder"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER As String = "subcluster"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_LABEL As String = "subclusterLabel"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_STYLE_NAME As String = "subclusterStyleName"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_ATTRIBUTES As String = "subclusterAttributes"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_TOOLTIP As String = "subclusterTooltip"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SUBCLUSTER_PLACEHOLDER As String = "subclusterPlaceholder"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_RECORDSET_PLACEHOLDER As String = "recordsetPlaceholder"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_SPLIT_LENGTH As String = "splitLength"
Public Const JSON_SETTINGS_SQL_FIELD_NAME_LINE_ENDING As String = "lineEnding"

Public Const JSON_SETTINGS_SQL_FILTER_COLUMN As String = "filterColumn"
Public Const JSON_SETTINGS_SQL_FILTER_VALUE As String = "filterValue"

Public Const JSON_SETTINGS_EXT_TAB_NAME As String = "tabName"
Public Const JSON_SETTINGS_EXT_TAB_GROUP_NAME_WEB As String = "webResources"
Public Const JSON_SETTINGS_EXT_TAB_GROUP_NAME_CODE As String = "customCode"

Public Const JSON_SETTINGS_SECTION_COLUMNS As String = "columns"
Public Const JSON_SETTINGS_SECTION_CONSOLE As String = "console"
Public Const JSON_SETTINGS_SECTION_DEBUG As String = "debug"
Public Const JSON_SETTINGS_SECTION_EDGES As String = "edges"
Public Const JSON_SETTINGS_SECTION_GRAPH As String = "graph"
Public Const JSON_SETTINGS_SECTION_GRAPH_TO_FILE As String = "graphToFile"
Public Const JSON_SETTINGS_SECTION_GRAPH_TO_WORKSHEET As String = "graphToWorksheet"
Public Const JSON_SETTINGS_SECTION_LANGUAGE As String = "language"
Public Const JSON_SETTINGS_SECTION_LAYOUT As String = "layout"
Public Const JSON_SETTINGS_SECTION_NODES As String = "nodes"
Public Const JSON_SETTINGS_SECTION_OPTIONS As String = "options"
Public Const JSON_SETTINGS_SECTION_STYLES As String = "styles"
Public Const JSON_SETTINGS_SECTION_WORKSHEETS As String = "worksheets"

Public Const JSON_SECTION_METADATA As String = "metadata"
Public Const JSON_SECTION_LAYOUTS As String = "layouts"
Public Const JSON_SECTION_SETTINGS As String = "settings"
Public Const JSON_SECTION_CONTENT As String = "content"

Public Const JSON_METADATA_NAME As String = "name"
Public Const JSON_METADATA_TYPE As String = "type"
Public Const JSON_METADATA_VERSION As String = "version"
Public Const JSON_METADATA_USER As String = "user"
Public Const JSON_METADATA_DATE As String = "date"
Public Const JSON_METADATA_TIME As String = "time"
Public Const JSON_METADATA_EXCEL As String = "excel"
Public Const JSON_METADATA_OS As String = "os"
Public Const JSON_METADATA_FILENAME As String = "filename"

Public Const JSON_METADATA_NAME_VALUE As String = "E2GXF"
Public Const JSON_METADATA_TYPE_VALUE As String = "Excel to Graphviz Exchange Format"
Public Const JSON_METADATA_VERSION_VERSION As String = "1.0"

Public Const JSON_LAYOUT_SQL_FLAG As String = "flag"
Public Const JSON_LAYOUT_SQL_SQL_STATEMENT As String = "sqlStatement"
Public Const JSON_LAYOUT_SQL_EXCEL_FILE As String = "excelFile"
Public Const JSON_LAYOUT_SQL_STATUS As String = "status"

Public Const JSON_LAYOUT_SVG_FLAG As String = "flag"
Public Const JSON_LAYOUT_SVG_FIND As String = "find"
Public Const JSON_LAYOUT_SVG_REPLACE As String = "replace"

Public Const JSON_WORKSHEETS_ABOUT As String = "about"
Public Const JSON_WORKSHEETS_ATTRIBUTES As String = "attributes"
Public Const JSON_WORKSHEETS_COLORS As String = "colors"
Public Const JSON_WORKSHEETS_CONSOLE As String = "console"
Public Const JSON_WORKSHEETS_DIAGNOSTICS As String = "diagnostics"
Public Const JSON_WORKSHEETS_EXCHANGE As String = "exchange"
Public Const JSON_WORKSHEETS_LISTS As String = "lists"
Public Const JSON_WORKSHEETS_LOCALE_DE_DE As String = "locale_de-DE"
Public Const JSON_WORKSHEETS_LOCALE_EN_GB As String = "locale_en-GB"
Public Const JSON_WORKSHEETS_LOCALE_EN_US As String = "locale_en-US"
Public Const JSON_WORKSHEETS_LOCALE_FR_FR As String = "locale_fr-FR"
Public Const JSON_WORKSHEETS_LOCALE_IT_IT As String = "locale_it-IT"
Public Const JSON_WORKSHEETS_LOCALE_PL_PL As String = "locale_pl-PL"
Public Const JSON_WORKSHEETS_SETTINGS As String = "settings"
Public Const JSON_WORKSHEETS_SHAPES As String = "shapes"
Public Const JSON_WORKSHEETS_SOURCE As String = "source"
Public Const JSON_WORKSHEETS_SQL As String = "sql"
Public Const JSON_WORKSHEETS_STYLE_DESIGNER As String = "styleDesigner"
Public Const JSON_WORKSHEETS_STYLES As String = "styles"
Public Const JSON_WORKSHEETS_SVG As String = "svg"

'@Ignore ConstantNotUsed
Public Const LOCALE_COL_ID As Long = 1
Public Const LOCALE_COL_LABEL_COMPACT As Long = 2
Public Const LOCALE_COL_LABEL_VERBOSE As Long = 3
Public Const LOCALE_COL_SCREENTIP As Long = 4
Public Const LOCALE_COL_SUPERTIP As Long = 5

' Localization IDs for identifiers used multiple times
Public Const MSGBOX_PRODUCT_TITLE As String = "msgboxProductTitle"

' File types
Public Const FILETYPE_SVG As String = "svg"

' Additional statements we treat like SQL
Public Const SQL_PREVIEW As String = "PREVIEW"
Public Const SQL_PREVIEW_AS_DIRECTED_GRAPH As String = "PREVIEW AS DIRECTED GRAPH"
Public Const SQL_PREVIEW_AS_UNDIRECTED_GRAPH As String = "PREVIEW AS UNDIRECTED GRAPH"
Public Const SQL_PUBLISH As String = "PUBLISH"
Public Const SQL_PUBLISH_ALL_VIEWS As String = "PUBLISH ALL VIEWS"
Public Const SQL_PUBLISH_ALL_VIEWS_AS_DIRECTED_GRAPH As String = "PUBLISH ALL VIEWS AS DIRECTED GRAPH"
Public Const SQL_PUBLISH_ALL_VIEWS_AS_UNDIRECTED_GRAPH As String = "PUBLISH ALL VIEWS AS UNDIRECTED GRAPH"
Public Const SQL_PUBLISH_AS_DIRECTED_GRAPH As String = "PUBLISH AS DIRECTED GRAPH"
Public Const SQL_PUBLISH_AS_UNDIRECTED_GRAPH As String = "PUBLISH AS UNDIRECTED GRAPH"
Public Const SQL_RESET As String = "RESET"
Public Const SQL_SELECT As String = "SELECT"
Public Const SQL_SET_DATA_FILE As String = "SET DATA FILE"

Public Const DIAGNOSTICS_WORKBOOK_NAME As String = "Diagnostics.WorkbookName"
Public Const DIAGNOSTICS_APPLICATION_OPERATING_SYSTEM As String = "Diagnostics.ApplicationOperatingSystem"
Public Const DIAGNOSTICS_APPLICATION_VERSION As String = "Diagnostics.Application.Version"
Public Const DIAGNOSTICS_GRAPHVIZ_VERSION As String = "Diagnostics.GraphvizVersion"
Public Const DIAGNOSTICS_APPLICATION_USER_NAME As String = "Diagnostics.ApplicationUserName"
Public Const DIAGNOSTICS_USERNAME As String = "Diagnostics.Username"
Public Const DIAGNOSTICS_TEMP_DIRECTORY As String = "Diagnostics.TempDirectory"
Public Const DIAGNOSTICS_TEMP_DIRECTORY_EXISTS As String = "Diagnostics.TempDirectoryExists"
Public Const DIAGNOSTICS_FONT_IMAGE_DIR As String = "Diagnostics.FontImageDir"
Public Const DIAGNOSTICS_FONT_IMAGE_DIR_EXISTS As String = "Diagnostics.FontImageDirExists"
Public Const DIAGNOSTICS_COLOR_IMAGE_DIR As String = "Diagnostics.ColorImageDir"
Public Const DIAGNOSTICS_COLOR_IMAGE_DIR_EXISTS As String = "Diagnostics.ColorImageDirExists"
Public Const DIAGNOSTICS_IMAGE_ENV_VARIABLE_NAME As String = "Diagnostics.ImageEnvVariableName"
Public Const DIAGNOSTICS_EXCELTOGRAPHVIZ_IMAGE_DIRECTORY As String = "Diagnostics.ExcelToGraphvizImageDirectory"
Public Const DIAGNOSTICS_EXCELTOGRAPHVIZ_IMAGE_DIRECTORY_EXISTS As String = "Diagnostics.ExcelToGraphvizImageDirectoryExists"
Public Const DIAGNOSTICS_IMAGE_PATH As String = "Diagnostics.ImagePath"
Public Const DIAGNOSTICS_IMAGE_PATH_EXISTS As String = "Diagnostics.ImagePathExists"
Public Const DIAGNOSTICS_APPLE_SCRIPT_FOLDER As String = "Diagnostics.AppleScriptFolder"
Public Const DIAGNOSTICS_APPLE_SCRIPT_FOLDER_EXISTS As String = "Diagnostics.AppleScriptFolderExists"
Public Const DIAGNOSTICS_APPLE_SCRIPT_FILE As String = "Diagnostics.AppleScriptFile"
Public Const DIAGNOSTICS_APPLE_SCRIPT_FILE_EXISTS As String = "Diagnostics.AppleScriptFileExists"
Public Const DIAGNOSTICS_APPLE_SCRIPT_VERSION As String = "Diagnostics.AppleScriptVersion"

